### ISSUE TITLE
documentation on how you implemented and deployed the project

### ISSUE THREAD

**Issue by sathishvj** [manekinekko/angularattack2016#22]
Could you please do a write up on how you started the project with any dependencies and manifest files, and then how you deployed it?  There is almost no documentation right now on how to make an ionic2 app also a pwa.

**Comment by manekinekko** [comment]
great suggestion. I'll add this to my list ;)

**Comment by sathishvj** [comment]
When I thought for myself how to do this, I figured that all that would be required would be to copy the manifest.json file and edit it for my purpose and then deploy the built www directory. Is that right? I guess it would be that simple.

**Comment by manekinekko** [comment]
yeah basically that's it.

**Comment by manekinekko** [comment]
@sathishvj here is the deployment story: https://medium.com/@wassimchegham/deploy-your-app-to-firebase-in-seconds-b3a9a37dff47

I'll publish the rest asap.
