### ISSUE TITLE
Not working with the current ionic version

### ISSUE THREAD

**Issue by kaelumania** [manekinekko/angularattack2016#24]
Following the README does not work with the current ionic version and newly released angular2

**Comment by manekinekko** [comment]
@attilacsanyi are you able to check this out?

**Comment by kaelumania** [comment]
that would be awesome I tried to get it working for a few hours now. Without success. Or maybe I should downgrade ionic cli? which version did you use?

**Comment by manekinekko** [comment]
This app is still using Ionic2 beta6 https://github.com/manekinekko/angularattack2016/blob/master/package.json#L17
